### ISSUE TITLE
Adding search filters

### ISSUE THREAD

**Issue by acecoder7** [SnowScriptWinterOfCode/ChefBook#12]
Adding filter feature for the recipes rendered from searching. 
Filter by-
calories
cooking time
cuisineType 
mealType
diet etc

kindly assign this feature addition to me. @Nitya-Pasrija @i-am-SnehaChauhan

**Comment by i-am-SnehaChauhan** [comment]
Hey @acecoder7 can u explain your issue and your approach to do that.

**Comment by acecoder7** [comment]
Issue description:
Adding a recipe filter functionality

Approach:
I will be utilizing the Edamam Recipe search API to add other response parameters as query to filter the search results

Demonstration of API working-

![Screenshot (526)](https://github.com/SnowScriptWinterOfCode/ChefBook/assets/98738210/de699cc8-cbc9-4226-99e0-bb01ec2cb037)
It is a simple 'spinach' keyword search which has 10000 recipes in response body

here
![Screenshot (527)](https://github.com/SnowScriptWinterOfCode/ChefBook/assets/98738210/74b2d3bc-0089-4b8a-bfd8-da8b155e324c)
here on adding dishType=drinks, we further filtered our search to all the spinach dishes with dishType as drink. Here, we get 1087 recipes in response body.


I hope this clears the issue as well as the approach.

**Comment by acecoder7** [comment]
> Hey @acecoder7 can u explain your issue and your approach to do that.

Issue description:
Adding a recipe filter functionality

Approach:
I will be utilizing the Edamam Recipe search API to add other response parameters as query to filter the search results

Demonstration of API working-

![Screenshot (526)](https://github.com/SnowScriptWinterOfCode/ChefBook/assets/98738210/de699cc8-cbc9-4226-99e0-bb01ec2cb037)
It is a simple 'spinach' keyword search which has 10000 recipes in response body

here
![Screenshot (527)](https://github.com/SnowScriptWinterOfCode/ChefBook/assets/98738210/74b2d3bc-0089-4b8a-bfd8-da8b155e324c)
here on adding dishType=drinks, we further filtered our search to all the spinach dishes with dishType as drink. Here, we get 1087 recipes in response body.


I hope this clears the issue as well as the approach.
